# Generated by Django 4.0.3 on 2022-07-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0002_alter_homepage_describtion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homePage',
        ),
    ]
