# Generated by Django 4.0.3 on 2022-07-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforme', '0003_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITC_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=20)),
                ('lastName', models.TextField(max_length=20)),
                ('age', models.IntegerField()),
                ('fiels_of_study', models.TextField(max_length=20)),
                ('position', models.CharField(choices=[('member', 'Member'), ('teamLeader', 'Teamleader'), ('membreBireau', 'Membrebireau'), ('ProjectManager', 'Projectmanager')], default='member', max_length=20)),
            ],
        ),
    ]
