# Generated by Django 4.0.3 on 2022-07-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITC_Members',
            new_name='ITC_Member',
        ),
    ]
