# Generated by Django 4.0.3 on 2022-07-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0005_rename_itc_members_itc_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itc_member',
            name='fiels_of_study',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='itc_member',
            name='firstName',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='itc_member',
            name='lastName',
            field=models.TextField(max_length=10),
        ),
    ]
